alter table workspaces add column organization_id uuid references organizations(id) on delete cascade;
alter table people add column organization_id uuid references organizations(id) on delete cascade;
alter table companies add column organization_id uuid references organizations(id) on delete cascade;
alter table deals add column organization_id uuid references organizations(id) on delete cascade;
alter table todos add column organization_id uuid references organizations(id) on delete cascade;
alter table activities add column organization_id uuid references organizations(id) on delete cascade;
alter table tags add column organization_id uuid references organizations(id) on delete cascade;
alter table email_accounts add column organization_id uuid references organizations(id) on delete cascade;
alter table email_messages add column organization_id uuid references organizations(id) on delete cascade;
alter table ai_prompts add column organization_id uuid references organizations(id) on delete cascade;
alter table assistant_conversations add column organization_id uuid references organizations(id) on delete cascade;
alter table person_emails add column organization_id uuid references organizations(id) on delete cascade;
alter table company_domains add column organization_id uuid references organizations(id) on delete cascade;
alter table suggestion_suppressions add column organization_id uuid references organizations(id) on delete cascade;
alter table person_companies add column organization_id uuid references organizations(id) on delete cascade;
alter table deal_people add column organization_id uuid references organizations(id) on delete cascade;
alter table deal_companies add column organization_id uuid references organizations(id) on delete cascade;
alter table activity_links add column organization_id uuid references organizations(id) on delete cascade;
alter table entity_tags add column organization_id uuid references organizations(id) on delete cascade;
alter table workspace_people add column organization_id uuid references organizations(id) on delete cascade;
alter table workspace_companies add column organization_id uuid references organizations(id) on delete cascade;

create index workspaces_organization_idx on workspaces (organization_id, updated_at desc);
create index people_organization_idx on people (organization_id, updated_at desc);
create index companies_organization_idx on companies (organization_id, updated_at desc);
create index deals_organization_idx on deals (organization_id, updated_at desc);
create index todos_organization_idx on todos (organization_id, status, due_at nulls last, created_at desc);
create index activities_organization_idx on activities (organization_id, occurred_at desc);
create index tags_organization_idx on tags (organization_id, name);
create index email_accounts_organization_idx on email_accounts (organization_id, created_at desc);
create index email_messages_organization_idx on email_messages (organization_id, sent_at desc);
create index ai_prompts_organization_idx on ai_prompts (organization_id, status, created_at desc);
create index assistant_conversations_organization_idx on assistant_conversations (organization_id, updated_at desc);

---- create above / drop below ----

drop index if exists assistant_conversations_organization_idx;
drop index if exists ai_prompts_organization_idx;
drop index if exists email_messages_organization_idx;
drop index if exists email_accounts_organization_idx;
drop index if exists tags_organization_idx;
drop index if exists activities_organization_idx;
drop index if exists todos_organization_idx;
drop index if exists deals_organization_idx;
drop index if exists companies_organization_idx;
drop index if exists people_organization_idx;
drop index if exists workspaces_organization_idx;

alter table workspace_companies drop column if exists organization_id;
alter table workspace_people drop column if exists organization_id;
alter table entity_tags drop column if exists organization_id;
alter table activity_links drop column if exists organization_id;
alter table deal_companies drop column if exists organization_id;
alter table deal_people drop column if exists organization_id;
alter table person_companies drop column if exists organization_id;
alter table suggestion_suppressions drop column if exists organization_id;
alter table company_domains drop column if exists organization_id;
alter table person_emails drop column if exists organization_id;
alter table assistant_conversations drop column if exists organization_id;
alter table ai_prompts drop column if exists organization_id;
alter table email_messages drop column if exists organization_id;
alter table email_accounts drop column if exists organization_id;
alter table tags drop column if exists organization_id;
alter table activities drop column if exists organization_id;
alter table todos drop column if exists organization_id;
alter table deals drop column if exists organization_id;
alter table companies drop column if exists organization_id;
alter table people drop column if exists organization_id;
alter table workspaces drop column if exists organization_id;
